import { StationInfo } from '../types/transport';

export const STATION_SEED_MAP: Record<string, StationInfo> = {
  mumbai: { name: 'Mumbai CSMT', code: 'CSTM', city: 'Mumbai' },
  cst: { name: 'Mumbai CSMT', code: 'CSTM', city: 'Mumbai' },
  'mumbai central': { name: 'Mumbai Central', code: 'MMCT', city: 'Mumbai' },
  delhi: { name: 'New Delhi', code: 'NDLS', city: 'Delhi' },
  'new delhi': { name: 'New Delhi', code: 'NDLS', city: 'Delhi' },
  bangalore: { name: 'KSR Bengaluru', code: 'SBC', city: 'Bengaluru' },
  bengaluru: { name: 'KSR Bengaluru', code: 'SBC', city: 'Bengaluru' },
  chennai: { name: 'Chennai Central', code: 'MAS', city: 'Chennai' },
  hyderabad: { name: 'Hyderabad Deccan', code: 'HYB', city: 'Hyderabad' },
  secunderabad: {
    name: 'Secunderabad Junction',
    code: 'SC',
    city: 'Hyderabad',
  },
  pune: { name: 'Pune Junction', code: 'PUNE', city: 'Pune' },
  kolkata: { name: 'Kolkata Howrah', code: 'HWH', city: 'Kolkata' },
  howrah: { name: 'Kolkata Howrah', code: 'HWH', city: 'Kolkata' },
  ahmedabad: { name: 'Ahmedabad Junction', code: 'ADI', city: 'Ahmedabad' },
  goa: { name: 'Madgaon Junction', code: 'MAO', city: 'Goa' },
  madgaon: { name: 'Madgaon Junction', code: 'MAO', city: 'Goa' },
  kochi: { name: 'Ernakulam Junction', code: 'ERS', city: 'Kochi' },
  ernakulam: { name: 'Ernakulam Junction', code: 'ERS', city: 'Kochi' },
  lucknow: { name: 'Lucknow Charbagh', code: 'LKO', city: 'Lucknow' },
  jaipur: { name: 'Jaipur Junction', code: 'JP', city: 'Jaipur' },
  varanasi: { name: 'Varanasi Junction', code: 'BSB', city: 'Varanasi' },
  amritsar: { name: 'Amritsar Junction', code: 'ASR', city: 'Amritsar' },
  surat: { name: 'Surat Junction', code: 'ST', city: 'Surat' },
  bhopal: { name: 'Bhopal Junction', code: 'BPL', city: 'Bhopal' },
  agra: { name: 'Agra Cantt', code: 'AGC', city: 'Agra' },
  patna: { name: 'Patna Junction', code: 'PNBE', city: 'Patna' },
};
