import type { Metadata } from 'next'
import Link from 'next/link'
import { FlaskConical, AlertTriangle, CheckCircle, Clock, ExternalLink, Info } from 'lucide-react'

export const metadata: Metadata = {
  title: 'Our Methodology | How TripSage Creates Itineraries & Estimates — TripSage',
  description: 'Understand how TripSage generates travel itineraries, budget estimates, and visa summaries. Learn our data sources, limitations, and how to verify travel information.',
  keywords: ['TripSage methodology', 'how TripSage works', 'AI itinerary methodology', 'travel data accuracy', 'visa information verification'],
  alternates: {
    canonical: 'https://tripsage.in/methodology',
  },
  robots: {
    index: true,
    follow: true,
  },
  openGraph: {
    title: 'Our Methodology | How TripSage Creates Itineraries & Estimates',
    description: 'Learn how TripSage generates AI itineraries, budget estimates, and visa summaries, and how you should verify the information before travelling.',
    url: 'https://tripsage.in/methodology',
    siteName: 'TripSage',
    images: [{ url: 'https://tripsage.in/logo.png', width: 1200, height: 630, alt: 'TripSage Methodology' }],
    locale: 'en_IN',
    type: 'website',
  },
  twitter: {
    card: 'summary_large_image',
    title: 'Our Methodology | TripSage',
    description: 'How TripSage creates itineraries, budget estimates, and visa summaries — and how to verify everything.',
    images: ['https://tripsage.in/logo.png'],
  },
}

const breadcrumbSchema = {
  '@context': 'https://schema.org',
  '@type': 'BreadcrumbList',
  itemListElement: [
    { '@type': 'ListItem', position: 1, name: 'Home', item: 'https://tripsage.in' },
    { '@type': 'ListItem', position: 2, name: 'Methodology', item: 'https://tripsage.in/methodology' },
  ],
}

const LAST_REVIEWED = 'September 2026'

export default function MethodologyPage() {
  return (
    <div className="min-h-screen bg-[#FFFBF7] flex flex-col">
      <script
        type="application/ld+json"
        dangerouslySetInnerHTML={{ __html: JSON.stringify(breadcrumbSchema) }}
      />

      {/* Navbar */}
      <nav className="glass-dark sticky top-0 z-50 px-6 py-4 flex items-center justify-between border-b border-[#E8E0D8]">
        <Link href="/" className="flex items-center gap-3">
          <img src="/logo.png" alt="TripSage" width={36} height={36} className="rounded-xl w-[36px] h-[36px] object-contain" />
          <span className="font-bold text-xl text-[#1A1A1A]">TripSage</span>
        </Link>
        <Link href="/" className="text-sm text-[#6B6B6B] hover:text-[#EA580C] transition-colors">← Back to Home</Link>
      </nav>

      {/* Breadcrumb */}
      <div className="max-w-4xl mx-auto px-6 pt-6 w-full">
        <nav aria-label="Breadcrumb" className="text-xs text-[#A1A1AA] flex items-center gap-1.5">
          <Link href="/" className="hover:text-[#EA580C] transition-colors">Home</Link>
          <span>/</span>
          <span className="text-[#6B6B6B]">Methodology</span>
        </nav>
      </div>

      {/* Hero */}
      <header className="max-w-4xl mx-auto px-6 pt-10 pb-8 w-full">
        <div className="inline-flex items-center gap-2 bg-[#FFF0E8] text-[#EA580C] text-xs font-semibold px-3 py-1.5 rounded-full mb-4">
          <FlaskConical size={12} />
          How We Work
        </div>
        <h1 className="text-3xl md:text-4xl font-bold text-[#1A1A1A] mb-4 leading-tight">
          Our Methodology
        </h1>
        <p className="text-[#6B6B6B] text-base md:text-lg leading-relaxed max-w-2xl">
          Transparency about how TripSage creates its content — and what you should verify independently before you travel.
        </p>
        <div className="flex items-center gap-2 mt-4 text-xs text-[#A1A1AA]">
          <Clock size={13} />
          <span>Last reviewed: <strong className="text-[#6B6B6B]">{LAST_REVIEWED}</strong></span>
        </div>
      </header>

      {/* Main */}
      <main className="flex-1 max-w-4xl mx-auto px-6 pb-16 w-full space-y-8">

        {/* Data Limitation Banner */}
        <div className="bg-[#FFF8F5] border border-[#FDDFC8] rounded-2xl p-5 flex gap-3">
          <AlertTriangle size={18} className="text-[#EA580C] flex-shrink-0 mt-0.5" />
          <div>
            <p className="text-sm font-semibold text-[#1A1A1A] mb-1">Important: AI-generated content has limitations</p>
            <p className="text-sm text-[#6B6B6B] leading-relaxed">
              TripSage content is generated by AI and reviewed by human editors. It is intended as a starting point, not a definitive guide. Prices, visa rules, and availability change frequently. Always verify critical information through official sources before you travel.
            </p>
          </div>
        </div>

        {/* Itineraries */}
        <section className="bg-white border border-[#E8E0D8] rounded-2xl p-6 md:p-8">
          <div className="flex items-center gap-2 mb-1">
            <h2 className="text-xl font-bold text-[#1A1A1A]">How Itineraries Are Created</h2>
            <span className="text-xs text-[#A1A1AA] ml-auto flex items-center gap-1"><Clock size={11} /> Last reviewed: {LAST_REVIEWED}</span>
          </div>
          <div className="w-12 h-0.5 bg-[#EA580C] mb-5 rounded-full" />
          <div className="space-y-4 text-[#6B6B6B] text-sm leading-relaxed">
            <p>
              TripSage itineraries are generated by a large language model (LLM) that has been trained on a broad corpus of travel knowledge. When you provide destination, duration, group size, travel style, and budget, the model constructs a day-by-day plan that:
            </p>
            <ul className="list-disc list-inside space-y-1.5 pl-1">
              <li>Sequences attractions logically by geography to minimise travel time</li>
              <li>Balances popular landmarks with local, off-the-beaten-path experiences</li>
              <li>Accounts for local opening hours, seasonal factors, and typical crowd levels</li>
              <li>Includes practical notes on transport between stops</li>
            </ul>
            <p>
              Itineraries are reviewed by the TripSage editorial team before being published as destination guides. AI-generated plans produced on-the-fly (in the trip planner) are not individually reviewed and should be treated as a draft starting point.
            </p>
            <div className="bg-[#F5F0EA] rounded-xl p-4 mt-2">
              <p className="text-xs font-semibold text-[#1A1A1A] mb-1">Limitation</p>
              <p className="text-xs text-[#6B6B6B]">The AI model's knowledge has a training cutoff. New attractions, closures, and changes to opening hours that occurred after the cutoff date may not be reflected. Always confirm attraction details directly with the venue.</p>
            </div>
          </div>
        </section>

        {/* Budget Estimates */}
        <section className="bg-white border border-[#E8E0D8] rounded-2xl p-6 md:p-8">
          <div className="flex items-center gap-2 mb-1">
            <h2 className="text-xl font-bold text-[#1A1A1A]">How Budget Estimates Are Generated</h2>
            <span className="text-xs text-[#A1A1AA] ml-auto flex items-center gap-1"><Clock size={11} /> Last reviewed: {LAST_REVIEWED}</span>
          </div>
          <div className="w-12 h-0.5 bg-[#EA580C] mb-5 rounded-full" />
          <div className="space-y-4 text-[#6B6B6B] text-sm leading-relaxed">
            <p>
              Budget estimates on TripSage are <strong className="text-[#1A1A1A]">illustrative ranges</strong>, not live price quotes. They are built from:
            </p>
            <ul className="list-disc list-inside space-y-1.5 pl-1">
              <li><strong className="text-[#1A1A1A]">Accommodation</strong> — typical per-night cost ranges for budget/mid-range/premium categories sourced from publicly available hotel pricing data</li>
              <li><strong className="text-[#1A1A1A]">Flights</strong> — approximate round-trip airfare ranges based on major Indian departure cities, using historical and aggregated fare data</li>
              <li><strong className="text-[#1A1A1A]">Food & Dining</strong> — per-day estimates based on destination cost-of-living benchmarks</li>
              <li><strong className="text-[#1A1A1A]">Local Transport</strong> — category-based estimates (taxi, metro, rental, etc.) for the destination city</li>
              <li><strong className="text-[#1A1A1A]">Activities</strong> — typical entry fees and tour costs for the recommended experiences</li>
            </ul>
            <div className="bg-[#F5F0EA] rounded-xl p-4 mt-2">
              <p className="text-xs font-semibold text-[#1A1A1A] mb-1">Limitation</p>
              <p className="text-xs text-[#6B6B6B]">Actual prices vary with travel dates, advance booking time, season, and availability. Budget figures on TripSage are updated periodically but are not live. Use them to set expectations and compare destinations — then check airline and hotel sites for live fares.</p>
            </div>
          </div>
        </section>

        {/* Visa Summaries */}
        <section className="bg-white border border-[#E8E0D8] rounded-2xl p-6 md:p-8">
          <div className="flex items-center gap-2 mb-1">
            <h2 className="text-xl font-bold text-[#1A1A1A]">How Visa Summaries Are Compiled</h2>
            <span className="text-xs text-[#A1A1AA] ml-auto flex items-center gap-1"><Clock size={11} /> Last reviewed: {LAST_REVIEWED}</span>
          </div>
          <div className="w-12 h-0.5 bg-[#EA580C] mb-5 rounded-full" />
          <div className="space-y-4 text-[#6B6B6B] text-sm leading-relaxed">
            <p>
              Visa summaries are compiled by the TripSage editorial team using the following sources:
            </p>
            <ul className="list-disc list-inside space-y-1.5 pl-1">
              <li>Official embassy and consulate websites of the destination country</li>
              <li>India Ministry of External Affairs (mea.gov.in) travel advisories</li>
              <li>FRRO (Foreigners Regional Registration Office) guidelines where applicable</li>
              <li>Official e-visa portals (e.g., baliindonesia-visa.com, thaievisa.go.th)</li>
            </ul>
            <p>
              Each visa guide page displays the date it was last reviewed. Visa rules change without notice — always verify with the official embassy or consulate before applying.
            </p>
            <div className="bg-[#FFF8F5] border border-[#FDDFC8] rounded-xl p-4 mt-2">
              <p className="text-xs font-semibold text-[#1A1A1A] mb-1">⚠ Critical limitation</p>
              <p className="text-xs text-[#6B6B6B]">Visa information on TripSage is informational only and does not constitute legal or immigration advice. TripSage is not responsible for visa decisions, rejections, or travel disruptions arising from reliance on information published here. Always obtain confirmation from the official embassy, consulate, or a licensed immigration advisor.</p>
            </div>
          </div>
        </section>

        {/* How to Verify */}
        <section className="bg-white border border-[#E8E0D8] rounded-2xl p-6 md:p-8">
          <h2 className="text-xl font-bold text-[#1A1A1A] mb-5">How to Verify Information Before You Travel</h2>
          <div className="space-y-4">
            {[
              {
                step: '1',
                title: 'Visa & entry requirements',
                desc: 'Check the official embassy or consulate website of your destination country. For Indian passport holders, also consult mea.gov.in.',
              },
              {
                step: '2',
                title: 'Flight prices',
                desc: 'Search airline websites directly (IndiGo, Air India, etc.) or flight aggregators (MakeMyTrip, Skyscanner) for live fares.',
              },
              {
                step: '3',
                title: 'Hotel availability & rates',
                desc: 'Check hotel websites directly or use booking platforms (Booking.com, Hotels.com). Rates shown on TripSage are indicative ranges.',
              },
              {
                step: '4',
                title: 'Attraction opening hours',
                desc: 'Verify with the official website of the attraction, especially for national holidays, seasonal closures, or ticketing changes.',
              },
            ].map((item) => (
              <div key={item.step} className="flex gap-4">
                <div className="w-7 h-7 rounded-full bg-[#FFF0E8] border border-[#FDDFC8] flex items-center justify-center flex-shrink-0 text-xs font-bold text-[#EA580C]">
                  {item.step}
                </div>
                <div>
                  <p className="text-sm font-semibold text-[#1A1A1A]">{item.title}</p>
                  <p className="text-sm text-[#6B6B6B] mt-0.5">{item.desc}</p>
                </div>
              </div>
            ))}
          </div>
          <div className="mt-6 pt-5 border-t border-[#E8E0D8]">
            <Link href="/sources" className="inline-flex items-center gap-2 text-sm font-semibold text-[#EA580C] hover:underline">
              View our Sources & References <ExternalLink size={13} />
            </Link>
          </div>
        </section>

        {/* Trust Links */}
        <section className="bg-[#F5F0EA] rounded-2xl p-6">
          <h2 className="text-base font-bold text-[#1A1A1A] mb-4">Related Pages</h2>
          <div className="flex flex-wrap gap-3">
            {[
              { href: '/about', label: 'About TripSage' },
              { href: '/editorial-policy', label: 'Editorial Policy' },
              { href: '/authors', label: 'Our Authors' },
              { href: '/sources', label: 'Sources & References' },
            ].map((link) => (
              <Link key={link.href} href={link.href} className="text-sm text-[#6B6B6B] hover:text-[#EA580C] hover:underline transition-colors">
                {link.label}
              </Link>
            ))}
          </div>
        </section>
      </main>

      <footer className="border-t border-[#E8E0D8] px-6 py-8">
        <div className="max-w-4xl mx-auto flex flex-col md:flex-row items-center justify-between gap-4">
          <div className="flex items-center gap-3">
            <span className="font-bold text-[#EA580C]">TripSage</span>
            <span className="text-[#A1A1AA] text-xs">— AI Travel Planning</span>
          </div>
          <div className="text-[#A1A1AA] text-xs">© {new Date().getFullYear()} TripSage. All rights reserved.</div>
        </div>
      </footer>
    </div>
  )
}
