import { StationInfo } from '../types/trains';

export const STATION_CODES: Record<string, StationInfo> = {
  mumbai: { name: 'Mumbai CSMT', code: 'CSTM', city: 'Mumbai' },
  'mumbai cst': { name: 'Mumbai CSMT', code: 'CSTM', city: 'Mumbai' },
  csmt: { name: 'Mumbai CSMT', code: 'CSTM', city: 'Mumbai' },
  cstm: { name: 'Mumbai CSMT', code: 'CSTM', city: 'Mumbai' },
  'mumbai central': { name: 'Mumbai Central', code: 'MMCT', city: 'Mumbai' },
  mmct: { name: 'Mumbai Central', code: 'MMCT', city: 'Mumbai' },
  delhi: { name: 'New Delhi', code: 'NDLS', city: 'Delhi' },
  'new delhi': { name: 'New Delhi', code: 'NDLS', city: 'Delhi' },
  ndls: { name: 'New Delhi', code: 'NDLS', city: 'Delhi' },
  bangalore: { name: 'KSR Bengaluru', code: 'SBC', city: 'Bengaluru' },
  bengaluru: { name: 'KSR Bengaluru', code: 'SBC', city: 'Bengaluru' },
  sbc: { name: 'KSR Bengaluru', code: 'SBC', city: 'Bengaluru' },
  chennai: { name: 'Chennai Central', code: 'MAS', city: 'Chennai' },
  mas: { name: 'Chennai Central', code: 'MAS', city: 'Chennai' },
  hyderabad: { name: 'Hyderabad Deccan', code: 'HYB', city: 'Hyderabad' },
  hyb: { name: 'Hyderabad Deccan', code: 'HYB', city: 'Hyderabad' },
  secunderabad: { name: 'Secunderabad Jn', code: 'SC', city: 'Hyderabad' },
  sc: { name: 'Secunderabad Jn', code: 'SC', city: 'Hyderabad' },
  pune: { name: 'Pune Junction', code: 'PUNE', city: 'Pune' },
  'pune jn': { name: 'Pune Junction', code: 'PUNE', city: 'Pune' },
  kolkata: { name: 'Kolkata Howrah', code: 'HWH', city: 'Kolkata' },
  hwh: { name: 'Kolkata Howrah', code: 'HWH', city: 'Kolkata' },
  ahmedabad: { name: 'Ahmedabad Junction', code: 'ADI', city: 'Ahmedabad' },
  adi: { name: 'Ahmedabad Junction', code: 'ADI', city: 'Ahmedabad' },
  jaipur: { name: 'Jaipur Junction', code: 'JP', city: 'Jaipur' },
  jp: { name: 'Jaipur Junction', code: 'JP', city: 'Jaipur' },
  goa: { name: 'Madgaon Junction', code: 'MAO', city: 'Goa' },
  madgaon: { name: 'Madgaon Junction', code: 'MAO', city: 'Goa' },
  mao: { name: 'Madgaon Junction', code: 'MAO', city: 'Goa' },
  kochi: { name: 'Ernakulam Junction', code: 'ERS', city: 'Kochi' },
  ernakulam: { name: 'Ernakulam Junction', code: 'ERS', city: 'Kochi' },
  ers: { name: 'Ernakulam Junction', code: 'ERS', city: 'Kochi' },
  lucknow: { name: 'Lucknow Charbagh', code: 'LKO', city: 'Lucknow' },
  lko: { name: 'Lucknow Charbagh', code: 'LKO', city: 'Lucknow' },
  patna: { name: 'Patna Junction', code: 'PNBE', city: 'Patna' },
  pnbe: { name: 'Patna Junction', code: 'PNBE', city: 'Patna' },
  bhopal: { name: 'Bhopal Junction', code: 'BPL', city: 'Bhopal' },
  bpl: { name: 'Bhopal Junction', code: 'BPL', city: 'Bhopal' },
  agra: { name: 'Agra Cantt', code: 'AGC', city: 'Agra' },
  agc: { name: 'Agra Cantt', code: 'AGC', city: 'Agra' },
  varanasi: { name: 'Varanasi Junction', code: 'BSB', city: 'Varanasi' },
  bsb: { name: 'Varanasi Junction', code: 'BSB', city: 'Varanasi' },
  amritsar: { name: 'Amritsar Junction', code: 'ASR', city: 'Amritsar' },
  asr: { name: 'Amritsar Junction', code: 'ASR', city: 'Amritsar' },
  surat: { code: 'ST', name: 'Surat Junction', city: 'Surat' },
  st: { code: 'ST', name: 'Surat Junction', city: 'Surat' },
  
  // Expanded major Indian stations for the top 100
  kanpur: { name: 'Kanpur Central', code: 'CNB', city: 'Kanpur' },
  cnb: { name: 'Kanpur Central', code: 'CNB', city: 'Kanpur' },
  nagpur: { name: 'Nagpur Junction', code: 'NGP', city: 'Nagpur' },
  ngp: { name: 'Nagpur Junction', code: 'NGP', city: 'Nagpur' },
  chandigarh: { name: 'Chandigarh Junction', code: 'CDG', city: 'Chandigarh' },
  cdg: { name: 'Chandigarh Junction', code: 'CDG', city: 'Chandigarh' },
  coimbatore: { name: 'Coimbatore Junction', code: 'CBE', city: 'Coimbatore' },
  cbe: { name: 'Coimbatore Junction', code: 'CBE', city: 'Coimbatore' },
  trivandrum: { name: 'Thiruvananthapuram Central', code: 'TVC', city: 'Thiruvananthapuram' },
  tvc: { name: 'Thiruvananthapuram Central', code: 'TVC', city: 'Thiruvananthapuram' },
  visakhapatnam: { name: 'Visakhapatnam Junction', code: 'VSKP', city: 'Visakhapatnam' },
  vskp: { name: 'Visakhapatnam Junction', code: 'VSKP', city: 'Visakhapatnam' },
  vijayawada: { name: 'Vijayawada Junction', code: 'BZA', city: 'Vijayawada' },
  bza: { name: 'Vijayawada Junction', code: 'BZA', city: 'Vijayawada' },
  guwahati: { name: 'Guwahati Junction', code: 'GHY', city: 'Guwahati' },
  ghy: { name: 'Guwahati Junction', code: 'GHY', city: 'Guwahati' },
  ranchi: { name: 'Ranchi Junction', code: 'RNC', city: 'Ranchi' },
  rnc: { name: 'Ranchi Junction', code: 'RNC', city: 'Ranchi' },
  dehradun: { name: 'Dehradun Junction', code: 'DDN', city: 'Dehradun' },
  ddn: { name: 'Dehradun Junction', code: 'DDN', city: 'Dehradun' },
  gwalior: { name: 'Gwalior Junction', code: 'GWL', city: 'Gwalior' },
  gwl: { name: 'Gwalior Junction', code: 'GWL', city: 'Gwalior' },
  allahabad: { name: 'Prayagraj Junction', code: 'PRYJ', city: 'Prayagraj' },
  prayagraj: { name: 'Prayagraj Junction', code: 'PRYJ', city: 'Prayagraj' },
  pryj: { name: 'Prayagraj Junction', code: 'PRYJ', city: 'Prayagraj' },
  jodhpur: { name: 'Jodhpur Junction', code: 'JU', city: 'Jodhpur' },
  ju: { name: 'Jodhpur Junction', code: 'JU', city: 'Jodhpur' },
  udaipur: { name: 'Udaipur City', code: 'UDZ', city: 'Udaipur' },
  udz: { name: 'Udaipur City', code: 'UDZ', city: 'Udaipur' },
  mysore: { name: 'Mysuru Junction', code: 'MYS', city: 'Mysuru' },
  mysuru: { name: 'Mysuru Junction', code: 'MYS', city: 'Mysuru' },
  mys: { name: 'Mysuru Junction', code: 'MYS', city: 'Mysuru' },
  haridwar: { name: 'Haridwar Junction', code: 'HW', city: 'Haridwar' },
  hw: { name: 'Haridwar Junction', code: 'HW', city: 'Haridwar' },
  tirupati: { name: 'Tirupati Junction', code: 'TPTY', city: 'Tirupati' },
  tpty: { name: 'Tirupati Junction', code: 'TPTY', city: 'Tirupati' },
  madurai: { name: 'Madurai Junction', code: 'MDU', city: 'Madurai' },
  mdu: { name: 'Madurai Junction', code: 'MDU', city: 'Madurai' },
};
