/**
 * Activities API Client
 *
 * Typed wrappers for all activities backend endpoints.
 * Follows the same pattern as lib/api.ts (tripAPI / authAPI).
 *
 * IMPORTANT: rateKey is NEVER exposed by backend — bookingId is the namespace.
 */

import type {
  ApiResponse,
} from './api'
import type {
  ActivitySearchParams,
  ActivitySearchResult,
  ActivityDetailsResult,
  PreconfirmPayload,
  PreconfirmResult,
  CreatePaymentOrderPayload,
  RazorpayOrderResult,
  VerifyPaymentPayload,
  ReconfirmPayload,
  ReconfirmResult,
  ActivityBookingRecord,
  CancelSimulationResult,
  CancelResult,
} from '@/types/activities'

import axios from 'axios'

const _ACT = axios.create({
  baseURL: process.env.NEXT_PUBLIC_API_URL,
  timeout: 60000,
  headers: { 'Content-Type': 'application/json' },
})

// Inject auth token + session ID
_ACT.interceptors.request.use((config) => {
  if (typeof sessionStorage !== 'undefined') {
    const sid = sessionStorage.getItem('sessionId')
    if (sid) config.headers['x-session-id'] = sid
  }
  if (!config.headers['Authorization'] && typeof localStorage !== 'undefined') {
    try {
      const raw    = localStorage.getItem('tripsage-auth')
      const parsed = raw ? JSON.parse(raw) : null
      const token  = parsed?.state?.token
      if (token) config.headers['Authorization'] = `Bearer ${token}`
    } catch { /* ignore */ }
  }
  return config
})

// Unwrap response envelope
_ACT.interceptors.response.use(
  (res) => res.data,
  (err) => {
    const msg = err.response?.data?.error || err.response?.data?.message || err.message || 'Something went wrong'
    return Promise.reject(new Error(msg))
  }
)

const ACT = _ACT as any

// ── Activities API ─────────────────────────────────────────────────────────────

export const activitiesAPI = {
  /**
   * Search for activities by destination / GPS / hotel code / keyword.
   */
  search: (
    params: ActivitySearchParams
  ): Promise<ApiResponse<ActivitySearchResult>> =>
    ACT.post('/api/activities/search', params),

  /**
   * Fetch full activity details and store the rateKey server-side (30-min TTL).
   * Returns everything except the rateKey itself — bookingId is the handle.
   *
   * @param bookingId — UUID generated by caller, used as rateKey namespace
   */
  getDetails: (
    bookingId: string,
    params: {
      activityCode: string
      fromDate:     string
      toDate:       string
      language?:    string
      paxes:        { age: number; type?: 'ADULT' | 'CHILD' | 'INFANT' }[]
    }
  ): Promise<ApiResponse<ActivityDetailsResult>> =>
    ACT.post('/api/activities/details', params, {
      headers: { 'x-booking-id': bookingId },
    }),

  /**
   * Create a preconfirmed booking reservation.
   * Requires a fresh bookingId that matches the one used in getDetails().
   */
  preconfirm: (
    payload: PreconfirmPayload
  ): Promise<ApiResponse<PreconfirmResult>> =>
    ACT.post('/api/activities/preconfirm', payload),

  /**
   * Reconfirm a preconfirmed booking after payment.
   * Backend verifies Razorpay signature internally before calling Hotelbeds.
   */
  reconfirm: (
    payload: ReconfirmPayload
  ): Promise<ApiResponse<ReconfirmResult>> =>
    ACT.post('/api/activities/reconfirm', payload),
}

// ── Payments API ──────────────────────────────────────────────────────────────

export const paymentsAPI = {
  /**
   * Create a Razorpay order for an activity booking.
   * Returns the order ID and public key ID for the Razorpay checkout modal.
   */
  createOrder: (
    payload: CreatePaymentOrderPayload
  ): Promise<ApiResponse<RazorpayOrderResult>> =>
    ACT.post('/api/payments/create-order', payload),

  /**
   * Verify the Razorpay payment signature after checkout modal success.
   * Call this BEFORE calling reconfirm.
   */
  verify: (
    payload: VerifyPaymentPayload
  ): Promise<ApiResponse<{ verified: boolean; bookingId: string }>> =>
    ACT.post('/api/payments/verify', payload),
}

// ── Bookings API ──────────────────────────────────────────────────────────────

export const bookingsAPI = {
  /**
   * List activity bookings with optional filters.
   */
  list: (params?: {
    status?:   string
    fromDate?: string
    toDate?:   string
    page?:     number
    limit?:    number
  }): Promise<ApiResponse<{ bookings: ActivityBookingRecord[]; total: number; page: number; limit: number }>> =>
    ACT.get('/api/bookings', { params }),

  /**
   * Get a single booking by bookingId (UUID) or Hotelbeds reference.
   */
  get: (
    reference: string,
    language?: string
  ): Promise<ApiResponse<ActivityBookingRecord>> =>
    ACT.get(`/api/bookings/${encodeURIComponent(reference)}`, { params: { language } }),

  /**
   * Simulate cancellation — get fee + refund amount without actually cancelling.
   */
  cancelSimulation: (
    reference: string,
    language?: string
  ): Promise<ApiResponse<CancelSimulationResult>> =>
    ACT.post(`/api/bookings/${encodeURIComponent(reference)}/cancel-simulation`, { language }),

  /**
   * Execute actual cancellation. Must pass confirmed=true after showing simulation.
   */
  cancel: (
    reference: string,
    language?: string,
    confirmed?: boolean
  ): Promise<ApiResponse<CancelResult>> =>
    ACT.post(`/api/bookings/${encodeURIComponent(reference)}/cancel`, { language, confirmed }),
}
